config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get 'log-in', to: 'sessions#new'
  post 'log-in', to: 'sessions#create'
  delete 'log-out', to: 'sessions#destroy'
  resources :users, only: [:show, :create]
  resources :posts do
    member do
      get :publish
    end
  end
  get 'sign-up', to: 'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  enum status: {draft:0, published: 1}
  belongs_to :user
  def self.by_date
    order('created_at DESC')
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :posts
  validates_presence_of :name, :email
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_user
  private

  def current_user
    @_current_user ||= session[:current_user_id] &&
    User.find_by(id: session[:current_user_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :not_logged_in, only: :new
  before_action :not_found, :incorrect_user, only: %i[edit update destroy publish]

  def index
    @posts = Post.all.by_date
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.'}
      else
        format.html { render :new, status: :unprocessable_entity}
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was updated."}
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
    flash[:notice] = 'Post was deleted.'
  end

  def edit
  end
  
  def publish
    @post.published!
    redirect_to post_path(@post)
    flash[:notice] = 'Post was published'
  end
  
  def not_logged_in
    redirect_to log_in_path unless current_user
    flash[:notice] = 'You must be logged in to publish.'
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :status, :user_id)
  end

  def not_found
    raise ActionController::RoutingError.new('Not Found') unless current_user
  end

  def incorrect_user
    @post = Post.find(params[:id])
    raise ActionController::RoutingError.new('Not Found') unless current_user && current_user == @post.user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user != nil && user.authenticate(params[:password])
      session[:current_user_id] = user.id
      redirect_to root_path
      flash[:notice] = 'Welcome back.'
    else
      redirect_to log_in_path
      flash[:notice] = 'Incorrect details provided'
    end
  end

  def destroy
    session.delete(:current_user_id)
    @_current_user = nil
    redirect_to root_path
    flash[:notice] = 'Goodbye.'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
      respond_to do |format|
        if @user.save
          format.html {redirect_to log_in_path(@user), notice: 'User was successfully created.'}
        else 
          format.html { render :new, status: :unprocessable_entity }
        end
      end    
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prevented this post from being saved:</h2>
      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>
<%= render "form", post: @post %>
<p>
  <%= link_to "All posts", root_path %>
</p>

app/views/posts/index.html.erb
<% if @_current_user %>
  <%= button_to 'Log Out', log_out_path(@_current_user), method: :delete %>
<% else %>
  <%= link_to 'Log In', log_in_path %>
  <%= link_to 'Sign Up', sign_up_path %>
<% end %>

<h1>Latest Posts</h1>
<ul>
  <% @posts.each do |post| %>
    <li>
      <%= link_to post.title, post_path(post) %>
      <%= post.user.name %>
    </li>
  <% end %>
</ul>

<p>
  <% if @_current_user %>
    <%= link_to 'Add New Post', new_post_path %>
  <% end %>
</p>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render "form", post: @post %>
<p>
  <%= link_to "All posts", root_path %>
</p>

app/views/posts/show.html.erb
<article>
 <header>
  <h1><%= @post.title %></h1>
  <p>by <%= link_to @post.user.name, user_path(@post.user)%></p>
  <p><%= @post.created_at %></p>
  <p>Status: <%= @post.status %></p>
  <p><%= @post.content %></p>
  </header>
  <footer>
   <p>Last updated on <%= @post.updated_at %></p>
   <% if @post.user == @_current_user %>
    <%= link_to 'Edit', edit_post_path(@post) %>
    <%= button_to "Delete", @post, method: :delete %>
    <% if @post.draft? %>
      <%= link_to 'Publish', publish_post_path(@post) %>
    <% end %>
  <% end %>
  </footer>
</article>
<p>
  <%= link_to "All posts", root_path %>
</p>

app/views/users/new.html.erb
<h2>Sign Up to MindUrFitness</h2>
<%= form_with(model: @user) do |form| %>
  <% if @user.errors.any? %>
    <h2><%= pluralize(@user.errors.count, "error") %> prevented the user from being saved:</h2>
    <ul>
      <% @user.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  <% end %>
  <div>
    <p>
      <%= form.label :name %>
      <%= form.text_field :name %>
    </p>
    <p>
      <%= form.label :email %>
      <%= form.email_field :email%>
    </p>
    <p>
      <%= form.label :password %>
      <%= form.password_field :password%>
    </p>
    <p>
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation %>
    </p>
    <p>
      <%= form.submit 'Sign Up' %>
    </p>
  <% end %>
  

app/views/users/show.html.erb
<h1>MindUrFitness Account</h1>
<h2><%= @user.name %></h2>
<p><%= @user.email %></p>